### ISSUE TITLE
hi there,

### ISSUE THREAD

**Issue by dextronomous** [graffitilogic/KeyScanner#6]
do you have this one compiled ready to test and use,
could really not make it work gmp.h this that. 
thanks a lot in advance.

**Comment by Dimitrius1** [comment]
> do you have this one compiled ready to test and use, could really not make it work gmp.h this that. thanks a lot in advance.

https://mega.nz/file/iWZSSDSI#BYWbyZl6gfdGbb-ERG9zl7FBDAqDXzjsBf9SlYsj1B0

**Comment by graffitilogic** [comment]
Hey!  I don't b/c I'm iterating pretty quickly with a bunch of generator ideas that may or may not be go-forward approaches.  Once I get to the point where a few of the generators are keepers or at least valued for further experimentation then I'll parameterize them to the commandline args and I consider that to be a good point to make a release binary. (Soon, probably).     

I can probably help you get your build env sorted though.  The /depends/gmp includes and headers are x64 includes.   Maybe the relative path isn't working?  If in MSVC ->right click KeyScanner, Properties, C/C++ check the additional Include Directories.  Same for Linker-> Additional Library Directories.     If you aren't on an x64 (maybe arm64) or your build config is x86, I could also see those references not working.      Best of luck!      Shoot a screenshot or build errors if you are still seeing issues.   

I don't mind sharing that my (working) path on the vm that I work on for this is C:\crypto\code\repos\KeyScanner   which should match content with the repo root here.  I thought I'd updated the paths to be relative but possible I missed one or didn't consider portability thoroughly.

I'm planning on cleaning up or renaming those ED, ED2, ED3, ED4 and duplicate generator methods this week and should be able to get them parameterized, then I'll make a binary and post.  Just doesn't make a ton of sense to do it right now b/c it is a bit of a copy-paste, remark-unremark mess in the current state with hardcoded values.
